
plugins {
	id 'java-library'
	id 'jacoco'
	id 'maven-publish'
}


group       = 'org.jaffre'
version     = '1.0.0-SNAPSHOT'
description = 'jaffre'

ext.buildCommit    = 'git describe --always --tags --dirty=-dirty'.execute().text.trim()
ext.buildTimestamp = java.time.format.DateTimeFormatter.ISO_INSTANT.format(java.time.Instant.now())
ext.buildJdk       = "${System.properties['java.version']} (${System.properties['java.vendor']} ${System.properties['java.vm.version']})"


java {
	sourceCompatibility = JavaVersion.VERSION_17
	targetCompatibility = JavaVersion.VERSION_17
}


repositories {
	mavenCentral()
}


dependencies {
	api 'org.slf4j:slf4j-api:2.0.+'
	api 'org.springframework:spring-core:5.+'
	api 'org.springframework:spring-context:5.+'

	testImplementation 'org.junit.jupiter:junit-jupiter-api:5.+'
	testImplementation 'junit:junit:4.+'

	testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.+'
	testRuntimeOnly 'org.junit.vintage:junit-vintage-engine:5.+'
}


jacocoTestReport {
	reports {
		xml.required  = true
		html.required = true
		csv.required  = false
	}
}


jar {
	manifest {
		from('src/main/resources/META-INF/MANIFEST.MF')
		attributes(
			'Specification-Title':    'jaffre',
			'Specification-Version':  '1.0',
			'Implementation-Title':   project.name,
			'Implementation-Version': archiveVersion.get(),
			'Build-Revision':         buildCommit,
			'Build-Timestamp':        buildTimestamp,
			'Build-Jdk':              buildJdk
		)
	}
}


publishing {
	publications {
		mavenJava(MavenPublication) {
			from components.java
		}
	}
}
